/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.analysis;

import prolixa.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTThis(TThis node);
    void caseTIs(TIs node);
    void caseTProgram(TProgram node);
    void caseTIt(TIt node);
    void caseTPresents(TPresents node);
    void caseTLet(TLet node);
    void caseTUs(TUs node);
    void caseTBegin(TBegin node);
    void caseTThat(TThat node);
    void caseTWould(TWould node);
    void caseTBe(TBe node);
    void caseTAll(TAll node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTMod(TMod node);
    void caseTAssign(TAssign node);
    void caseTEqual(TEqual node);
    void caseTEq(TEq node);
    void caseTNeq(TNeq node);
    void caseTLe(TLe node);
    void caseTGe(TGe node);
    void caseTLt(TLt node);
    void caseTGt(TGt node);
    void caseTLpar(TLpar node);
    void caseTRpar(TRpar node);
    void caseTLbracket(TLbracket node);
    void caseTRbracket(TRbracket node);
    void caseTComma(TComma node);
    void caseTColon(TColon node);
    void caseTSemicolon(TSemicolon node);
    void caseTDot(TDot node);
    void caseTTimes(TTimes node);
    void caseTNumero(TNumero node);
    void caseTIdentificador(TIdentificador node);
    void caseTTipoPrimitivo(TTipoPrimitivo node);
    void caseTKwAlterable(TKwAlterable node);
    void caseTKwUnalterable(TKwUnalterable node);
    void caseTKwVector(TKwVector node);
    void caseTKwOf(TKwOf node);
    void caseTVazio(TVazio node);
    void caseTComentarioBloco(TComentarioBloco node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
