/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class TKwOf extends Token
{
    public TKwOf()
    {
        super.setText("of");
    }

    public TKwOf(int line, int pos)
    {
        super.setText("of");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwOf(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwOf(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwOf text.");
    }
}
