/* This file was generated by SableCC (http://www.sablecc.org/). */

package prolixa.node;

import prolixa.analysis.*;

@SuppressWarnings("nls")
public final class TKwVector extends Token
{
    public TKwVector()
    {
        super.setText("vector");
    }

    public TKwVector(int line, int pos)
    {
        super.setText("vector");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKwVector(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKwVector(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKwVector text.");
    }
}
